#  look at this example 

services:
    server:
        container_name: EphemeralEnvironments
        build:
            dockerfile: ./Dockerfile
            context: .
            args:
                GO_VERSION: 1.19
                HUGO_VERSION: 0.114.1
        volumes:
            - .:./app
        ports:
            - 3000:3000
