version: "3"
services:
  server:
    container_name: EphemeralEnvironments
    build:
      context: .
      args:
        GO_VERSION: 1.19
        HUGO_VERSION: 0.114.1
    volumes:
      - .:/app
    ports:
      - 1313:1313
